name: Push Events
on:
  schedule:
    - cron: '*/5 * * * *' #every 5 minutes
  push:
    branches:
      - main
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
    - name: Info
      run: |
        echo "This is a push event on all the branches"
      
