name: Manual Workflow
on:
  issues:
    types:
      - opened
jobs:
  run-manual-tasks:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
    - name: Info 
      run: |
        echo "running manual tasks"
